### ISSUE TITLE
Text color issue in menu

### ISSUE THREAD

**Issue by ianbrandt** [arrow-kt/arrow-website#147]
The "Quikstart" entry is white on a light gray background, so rather hard to see.

https://arrow-kt.io/learn/quickstart/

![image](https://user-images.githubusercontent.com/709570/229790615-f4299b30-0de9-4695-8709-018f9798ae35.jpeg)

**Comment by serras** [comment]
Interesting, because I have the opposite problem now: the color of the heading in the menus are too dark.
![Captura de pantalla 2023-04-05 a las 9 20 10](https://user-images.githubusercontent.com/309334/230009409-95fb1bee-7977-4301-8729-ba1b17ff0e27.png)

**Comment by calvellido** [comment]
This is being worked on, thanks!
