### ISSUE TITLE
RSS Feed Request

### ISSUE THREAD

**Issue by raulraja** [arrow-kt/arrow-website#153]
Request originating from https://kotlinlang.slack.com/archives/C0BJ0GTE2/p1680605898567299?thread_ts=1680604869.354969&cid=C0BJ0GTE2 , Konstantin Tskhovrebov suggested an RSS feed for the blog section

**Comment by calvellido** [comment]
As shared with Konstantin in the Kotlin Slack channel, RSS feed can be found in:

https://arrow-kt.io/community/blog/rss.xml
https://arrow-kt.io/community/blog/atom.xml


I will wait for feedback on there until I close the issue.

**Comment by nomisRev** [comment]
Should we put a RSS/Atom reference to that in the footer so that it's easy to find?

**Comment by calvellido** [comment]
> Should we put a RSS/Atom reference to that in the footer so that it's easy to find?

Yes, that sounds like a good idea :+1:
