### ISSUE TITLE
[Question] `parMap` and `parZip`

### ISSUE THREAD

**Issue by Kaaveh** [arrow-kt/arrow-website#233]
In the naming of `parMap` and `parZip`, the `par` stand for which word?

**Comment by serras** [comment]
It should remind of “parallel”, because it allows for the different computations to happen concurrently.

It also connects to similar wording in other programming communities. For example, Haskell follows a similar convention.

**Comment by Kaaveh** [comment]
Interesting! Thanks Ale.
