### ISSUE TITLE
Export code color scheme

### ISSUE THREAD

**Issue by asuras-coding** [arrow-kt/arrow-website#271]
Hey there,
I really like the color scheme used by the code blocks. It would be awesome if you could somehow make it available to use in IDEs (pref. IntelliJ).
If not, I want to ask if it's okay to use the colors as a base for a custom color scheme and to publish it somewhere (and maybe referring to the arrow project or not)

**Comment by raulraja** [comment]
>If not, I want to ask if it's okay to use the colors as a base for a custom color scheme and to publish it somewhere (and maybe referring to the arrow project or not)

Yes, that is fine. Feel free to use the color for your own scheme, and we'd love if you mention Arrow, thank you @asuras-coding
